export type EmojiRec = [string, string]

export const smileys: EmojiRec[] = [
    ['😀', 'Grinning Face'],
    ['😁', 'Grinning Face with Smiling Eyes'],
    ['😂', 'Face with Tears of Joy'],
    ['🙂', 'Slightly Smiling Face'],
    ['😉', 'Winking Face'],
    ['😊', 'Smiling Face with Smiling Eyes'],
    ['🥰', 'Smiling Face with Smiling Eyes and Three Hearts'],
    ['😍', 'Smiling Face with Heart-Shaped Eyes'],
    ['🤩', 'Grinning Face with Star Eyes'],
    ['😏', 'Smirking Face'],
    ['🤪', 'Grinning Face with One Large and One Small Eye'],
    ['🤭', 'Smiling Face with Smiling Eyes and Hand Covering Mouth'],
    ['🤤', 'Drooling Face'],
    ['🥳', 'Face with Party Horn and Party Hat'],
    ['😎', 'Smiling Face with Sunglasses'],
    ['🧐', 'Face with Monocle'],
    ['🤐', 'Zipper-Mouth Face'],
    ['🤨', 'Face with One Eyebrow Raised'],
    ['😐', 'Neutral Face'],
    ['😒', 'Unamused Face'],
    ['🙄', 'Face with Rolling Eyes'],
    ['😬', 'Grimacing Face'],
    ['😴', 'Sleeping Face'],
    ['🤢', 'Nauseated Face'],
    ['🥱', 'Yawning Face'],
    ['😕', 'Confused Face'],
    ['🙁', 'Slightly Frowning Face'],
    ['😲', 'Astonished Face'],
    ['😢', 'Crying Face'],
    ['😠', 'Angry Face'],
    ['😈', 'Smiling Face with Horns'],
    ['👽', 'Extraterrestrial Alien'],
]

export const hands: EmojiRec[] = [
    ['✋', 'Raised Hand'],
    ['👌', 'OK Hand Sign'],
    ['✌️', 'Victory Hand'],
    ['🤞', 'Hand with Index and Middle Fingers Crossed'],
    ['🤙', 'Call Me Hand'],
    ['👉', 'White Right Pointing Backhand Index'],
    ['☝️', 'White Up Pointing Index'],
    ['👍', 'Thumbs Up Sign'],
    ['👎', 'Thumbs Down Sign'],
    ['✊', 'Raised Fist'],
    ['🤝', 'Handshake'],
    ['🙏', 'Person with Folded Hands'],
]

export const symbols: EmojiRec[] = [
    ['💕', 'Two Hearts'],
    ['💔', 'Broken Heart'],
    ['❤️', 'Heavy Black Heart'],
    ['💭', 'Thought Balloon'],
    ['⚠️', 'Warning Sign'],
    ['♾️', 'Permanent Paper Sign'],
    ['✔️', 'Heavy Check Mark'],
    ['❌', 'Cross Mark'],
]
